[package]
name = "events-protobuf"
version = "0.1.0"
description = "Beep crate that manages Protobuf definitions for our async messages."
edition = "2024"

[dependencies]
prost = "0.14.1"

[build-dependencies]
prost-build = "0.14.1"
walkdir = "2.5.0"
