name: Validate Protobuf

on:
  push:
  pull_request:

jobs:
  validate_protobuf:
    name: Cargo Build & Test
    uses: beep-industries/actions/.github/workflows/validate-rust.yml@main
    with:
      toolchain: stable
      install-protoc: true

